
name: Build Android AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip python3-setuptools git zip unzip openjdk-17-jdk \
            libffi-dev libssl-dev libsqlite3-dev zlib1g zlib1g-dev \
            libjpeg-dev libpng-dev build-essential

      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip

      - name: Install buildozer & cython
        run: |
          pip install Cython==0.29.36
          pip install buildozer

      - name: Build AAB
        run: |
          buildozer android release

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-aab
          path: bin/*.aab
